### PR TITLE
Adds travis support (#7)

### PR DESCRIPTION
**Pull request by the-pat**

### CODE REVIEW

**Comment by lu-zero** [comment]
```
  = note: /usr/bin/ld: /usr/local/lib/libaom.a(aom_codec.c.o): relocation R_X86_64_32 against `.rodata.str1.1' can not be used when making a shared object; recompile with -fPIC
```

Looks like you are not enabling PIC.

**Comment by lu-zero** [comment]
Try passing `-DBUILD_SHARED_LIBS=1`.

**Comment by lu-zero** [comment]
either run `ldconfig` might fix it or pass `/usr` as prefix...

**Comment by the-pat** [comment]
@lu-zero, that did the trick! Thanks for all of your help!

**Comment by lu-zero** [comment]
Thanks to you :)

**Pull request merged**
